### ISSUE TITLE
Update readme

### ISSUE THREAD

**Issue by navaneeth-spotnana** [Compile-Time/demo-tracing-in-spring-boot-2-and-3#1]
https://github.com/Compile-Time/demo-tracing-in-spring-boot-2-and-3/blob/0a1d7c496a952e618c1f4640278f9d3686ad5492/sleuth-annotation-port/README.md?plain=1#L10

Micrometer team has added support for these annotations starting Springboot 3.1.0 / micrometer-tracing 1.1.0.

https://micrometer.io/docs/tracing

**Comment by navaneeth-spotnana** [comment]
SB 3.1.0 is not GA yet, so thanks for the repo, would help me a lot. Kindly let me know if you have used the custom implementation in production and found any gotchas, as I am going to attempt to do the same.

**Comment by Compile-Time** [comment]
Hi, thank you for the issue and the news!

I have not been in the situation yet where I needed to migrate a Spring Boot 2 tracing code base to Spring Boot 3. Therefore, I can not provide you with any insights or wisdom regarding this.

However, I pushed a new branch (`feature/micrometer-1.1.0-spring-boot-3.0.0`) where I tried to get Spring Boot 3.0.0 to work with Micrometer Tracing 1.1.0 by manually overriding the micrometer dependencies.

I changed/added the following dependencies.
```
// Needed for the SpelTagValueExpressionResolver.
implementation 'org.springframework.cloud:spring-cloud-sleuth-instrumentation:3.0.0'

// Overwrite micrometer version
implementation "io.micrometer:micrometer-tracing:1.1.0"
implementation "io.micrometer:micrometer-commons:1.11.0"

// Tracing dependencies after Spring Boot 3
implementation "io.micrometer:micrometer-tracing-bridge-brave:1.1.0"
```

Then I copied the example from the [Micrometer docs](https://micrometer.io/docs/tracing#_aspect_oriented_programming_starting_from_micrometer_tracing_1_1_0)

And created a wrapper class for the `SpelTagValueExpressionResolver` because in Spring Boot 3.0.0 it does not implement the `ValueExpressionResolver` which is needed for Micrometer Tracing 1.1.0.

```java
public class MicrometerSpelTagValueExpressionResolverWrapper implements ValueExpressionResolver {

    private final SpelTagValueExpressionResolver spelTagValueExpressionResolver;

    public MicrometerSpelTagValueExpressionResolverWrapper(SpelTagValueExpressionResolver spelTagValueExpressionResolver) {
        this.spelTagValueExpressionResolver = spelTagValueExpressionResolver
    }

    @Override
    public String resolve(String expression, Object parameter) {
        return spelTagValueExpressionResolver.resolve(expression, parameter);
    }
}
```

The wrapper is then used in place of the `SpelTagValueExpressionResolver` in the configuration class.

```java
@Bean
public ValueExpressionResolver valueExpressionResolver() {
    return new MicrometerSpelTagValueExpressionResolverWrapper(new SpelTagValueExpressionResolver());
}
```

Nonetheless, I don't think either re-implementing the Sleuth APIs or overriding the dependencies is a good idea. I think it would be better to postpone the upgrade till Spring Boot 3.1.0 goes GA or to use a release candidate if re-working you tracing code to the new API is not an option.

If you really can not wait, I think it would be quicker and better to overwrite the dependencies than to re-implement the Sleuth APIs.

**Comment by Compile-Time** [comment]
Closing: The READMEs of the different branches were updated to mention the news/announcement.
